### PR TITLE
Improved domain name pattern

### PR DESCRIPTION
**Pull request by octonato**
This PR brings here what I have pushed to 
https://github.com/akka/akka/pull/26332

We only copy-n-paste it here becasue we don't want to need to wait for a new Akka release. 
We should remove this class once https://github.com/akka/akka/pull/26332 gets merged and released.

We can also wait for https://github.com/akka/akka/pull/26332 to be merged before merging this one. We must make sure that the code is exactly the same.

### CODE REVIEW

**Comment by dwijnand** [comment]
Should've made it a draft pull request then 😉

**Comment by octonato** [comment]
> Should've made it a draft pull request then 😉

It's marked as WIP

**Comment by dwijnand** [comment]
I know but that requires enforcement.  A draft PR is enforced by GitHub itself.  JFYI.

**Review by marcospereira — APPROVED** [review]
LGTM.

**Pull request merged**
