### PR TITLE
Lagom 1.5.0

### PR DESCRIPTION
**Pull request by octonato**

### CODE REVIEW

**Comment by ignasi35** [comment]
I think we shouldn't bump this dependency or, instead, we should create a `1.4.x` branch before this change is merged.

**Comment by octonato** [comment]
We don't have plans to support it for 1.4.x

**Review by ignasi35 — APPROVED** [review]

**Comment by TimMoore** [comment]
> We don't have plans to support it for 1.4.x

Sorry, @renatocaval but this is not what we have previously discussed or agreed on. We said that it would be compatible with 1.4.x so that people who are currently using Lightbend Orchestration can migrate from that to this project first, before updating to Lagom 1.5. We published this information in the [Lightbend Orchestration Migration Guide](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html#service-discovery) this week, so I don't want to change that now. Can we change this back to build against 1.4.x? What's the benefit of updating it, just to reduce testing surface area?

I think our options here are:

1. Build, test and release against 1.4.latest and assume that it will work with 1.5.x because 1.5.x is backward compatible. Rely on downstream example projects such as shopping-cart for integration testing with 1.5x.
2. Build and release against 1.4.latest and test with both 1.4.x and 1.5.x by allowing the dependency to be overridden by a system property. Set up two Travis jobs to test each dependency.
3. Split this project into a 1.0.x branch targeting Lagom 1.4.x and a master branch targeting 1.5.x. Backport fixes that apply to both.

**Comment by octonato** [comment]
I don't remember that we have agreed so, on the contrary. Anyways, as it is now, it's also compatible with 1.4.x.

I would prefer to not have a 1.4.x branch because is one more branch to maintain. 

We don't have integration tests on this project. Either we add it and run it against 1.4.x and 1.5.x or we use a downstream project. Maybe the easiest is to tests here for both so we can detect any breakage as soon as possible.

**Pull request merged**
